Solution_1
mate-academy/py-lockdown-cafe pull request #82
Opened 2022-08-03 19:19 UTC by VladyslavKlevanskyi

2022-08-04 07:32 UTC, IvanRamyk requested changes

2022-08-04 07:32 UTC, IvanRamyk commented on app/main.py
> +    else:
Please, remove the redundant else

2022-08-04 07:32 UTC, IvanRamyk commented on app/cafe.py
> +        else:
Please, remove the redundant else

2022-08-05 07:32 UTC, IvanRamyk approved these changes
Well done!

2022-08-09 15:01 UTC, Abnormaltype approved these changes

2025-01-16 03:24 UTC, closed without merging